[package]
name = "substring-match"
version = "0.1.1"
edition = "2021"

[lib]
name = "substring_match"
crate-type = ["cdylib"]

[dependencies]
suffix = "1.3"

[dependencies.pyo3]
version = "0.17"
features = ["extension-module", "abi3-py37"]
